version: '3.9'

services:
  # easy-auth:
  #   build: ./
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - db
  #   links:
  #     - db
  #   restart: on-failure
  #   environment:
  #     - DB_PASSWORD=qwerty

  db:
    restart: always
    image: postgres:latest
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5432:5432
